# Generated by Django 5.1 on 2024-08-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('temperamento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canil.raca')),
            ],
        ),
    ]
