# Generated by Django 5.1 on 2024-08-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cachorros', to='canil.raca'),
        ),
    ]
